version: "3.9"
services:
  deploy:
    container_name: TMSlocal
    build:
      context: main
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://TMSdb:5432/tms_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      tmsapp-network:
        aliases:
          - TMSnet
networks:
  tmsapp-network:
    name: 'tms-network'